=== markus-bcit/term1/Term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/order.dtd
<!ELEMENT Orderdata (Order+)>
<!ELEMENT Order (ORD_ID,ORD_DATE,CUS_ID,PMT_ID,SHIP_ID,ORD_SHIPDATE,ORD_SHIPCOST,ORD_PRODCOST,
 ORD_TAXCOST,PROMO_ID?,ORD_TOTCOST,ORD_STATUS,ORDLINE+)>
<!ELEMENT ORD_ID (#PCDATA)>
<!ELEMENT ORD_DATE (#PCDATA)>
<!ELEMENT CUS_ID (#PCDATA)>
<!ELEMENT PMT_ID (#PCDATA)>
<!ELEMENT SHIP_ID (#PCDATA)>
<!ELEMENT ORD_SHIPDATE (#PCDATA)>
<!ELEMENT ORD_SHIPCOST (#PCDATA)>
<!ELEMENT ORD_PRODCOST (#PCDATA)>
<!ELEMENT ORD_TAXCOST (#PCDATA)>
<!ELEMENT PROMO_ID (#PCDATA)>
<!ELEMENT ORD_TOTCOST (#PCDATA)>
<!ELEMENT ORD_STATUS (#PCDATA)>
<!ELEMENT ORDLINE (PROD_ID,ORL_QTY,ORL_PRICE,ORL_TAX)>
<!ELEMENT PROD_ID (#PCDATA)>
<!ELEMENT ORL_QTY (#PCDATA)>
<!ELEMENT ORL_PRICE (#PCDATA)>
<!ELEMENT ORL_TAX (#PCDATA)>

=== markus-bcit/term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/order.xml
<?xml version ="1.0"?>
<!DOCTYPE Orderdata SYSTEM "Order.dtd">
<Orderdata>
<Order>
<ORD_ID>34523</ORD_ID>
<ORD_DATE>12/08/2015</ORD_DATE>
<CUS_ID>1010</CUS_ID>
<PMT_ID>VISA</PMT_ID>
<SHIP_ID>UPS GRND</SHIP_ID>
<ORD_SHIPDATE>12/12/2015</ORD_SHIPDATE>
<ORD_SHIPCOST>6.70</ORD_SHIPCOST>
<ORD_PRODCOST>59.00</ORD_PRODCOST>
<ORD_TAXCOST>5.90</ORD_TAXCOST>
<ORD_TOTCOST>64.90</ORD_TOTCOST>
<ORD_STATUS>SHIPPED</ORD_STATUS>
<ORDLINE>
<PROD_ID>QWERT-456</PROD_ID>
<ORL_QTY>10</ORL_QTY>
<ORL_PRICE>2.50</ORL_PRICE>
<ORL_TAX>Y</ORL_TAX>
</ORDLINE>
<ORDLINE>
<PROD_ID>TB670</PROD_ID>
<ORL_QTY>5</ORL_QTY>
<ORL_PRICE>6.80</ORL_PRICE>
<ORL_TAX>Y</ORL_TAX>
</ORDLINE>
</Order>
<Order>
<ORD_ID>34576</ORD_ID>
<ORD_DATE>12/08/2015</ORD_DATE>
<CUS_ID>2540</CUS_ID>
<PMT_ID>VISA</PMT_ID>
<SHIP_ID>UPS GRND</SHIP_ID>
<ORD_SHIPDATE>12/11/2015</ORD_SHIPDATE>
<ORD_SHIPCOST>6.50</ORD_SHIPCOST>
<ORD_PRODCOST>12.50</ORD_PRODCOST>
<ORD_TAXCOST>1.25</ORD_TAXCOST>
<ORD_TOTCOST>13.25</ORD_TOTCOST>
<ORD_STATUS>SHIPPED</ORD_STATUS>
<ORDLINE>
<PROD_ID>QWERT-456</PROD_ID>
<ORL_QTY>5</ORL_QTY>
<ORL_PRICE>2.50</ORL_PRICE>
<ORL_TAX>Y</ORL_TAX>
</ORDLINE>
</Order>
</Orderdata>
