=== markus-bcit/term1/Term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/product.dtd
<!ELEMENT Productdata (Product+)>
<!ELEMENT Product (PROD_ID,PROD_NAME,PROD_DESCR,PROD_OPTIONS*,PROD_SKU,PROD_PARTNUM,VEND_ID,
 PTYPE_ID,PROD_QOH,PROD_PRICE,PROD_MSRP,PROD_PRICE_D1,PROD_PRICE_D2,
 PROD_TAX)>
<!ELEMENT PROD_ID  (#PCDATA)>
<!ELEMENT PROD_NAME  (#PCDATA)>
<!ELEMENT PROD_DESCR  (#PCDATA)>
<!ELEMENT PROD_OPTIONS  (#PCDATA)>
<!ELEMENT PROD_SKU  (#PCDATA)>
<!ELEMENT PROD_PARTNUM  (#PCDATA)>
<!ELEMENT VEND_ID  (#PCDATA)>
<!ELEMENT PTYPE_ID  (#PCDATA)>
<!ELEMENT PROD_QOH  (#PCDATA)>
<!ELEMENT PROD_PRICE  (#PCDATA)>
<!ELEMENT PROD_MSRP  (#PCDATA)>
<!ELEMENT PROD_PRICE_D1  (#PCDATA)>
<!ELEMENT PROD_PRICE_D2  (#PCDATA)>
<!ELEMENT PROD_TAX  (#PCDATA)>

=== markus-bcit/term1/Term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/product.xml
<?xml version ="1.0"?>
<!DOCTYPE Productdata SYSTEM "Product.dtd">
<Productdata>
<Product>
<PROD_ID>QWERT-456</PROD_ID>
<PROD_NAME>Drill-Bit 2"</PROD_NAME>
<PROD_DESCR>Heavy Duty Stainless Steel Drill Bit 2"</PROD_DESCR>
<PROD_SKU>234R56T</PROD_SKU>
<PROD_PARTNUM>GH678</PROD_PARTNUM>
<VEND_ID>3451</VEND_ID>
<PTYPE_ID>Tools</PTYPE_ID>
<PROD_QOH>124</PROD_QOH>
<PROD_PRICE>2.50</PROD_PRICE>
<PROD_MSRP>3.20</PROD_MSRP>
<PROD_PRICE_D1>2.45</PROD_PRICE_D1>
<PROD_PRICE_D2>2.35</PROD_PRICE_D2>
<PROD_TAX>Y</PROD_TAX>
</Product>
<Product>
<PROD_ID>TB670</PROD_ID>
<PROD_NAME>Tool Box</PROD_NAME>
<PROD_DESCR>Tool Box Ergonomic Handle</PROD_DESCR>
<PROD_OPTIONS>Gray</PROD_OPTIONS>
<PROD_OPTIONS>Black</PROD_OPTIONS>
<PROD_SKU>YT58T</PROD_SKU>
<PROD_PARTNUM>2RTB56</PROD_PARTNUM>
<VEND_ID>3451</VEND_ID>
<PTYPE_ID>Tools</PTYPE_ID>
<PROD_QOH>21</PROD_QOH>
<PROD_PRICE>6.80</PROD_PRICE>
<PROD_MSRP>10.00</PROD_MSRP>
<PROD_PRICE_D1>6.50</PROD_PRICE_D1>
<PROD_PRICE_D2>6.20</PROD_PRICE_D2>
<PROD_TAX>Y</PROD_TAX>
</Product>
</Productdata>
