=== markus-bcit/term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/customer.dtd
<!ELEMENT Customerdata (Customer+)>
<!ELEMENT Customer (CUS_ID,CUS_DATEIN,CUS_LNAME,CUS_FNAME,CUS_ADDR1,CUS_ADDR2?,
CUS_CITY,CUS_STATE,CUS_ZIP,CUS_CNTRY?,CUS_PHONE,CUS_EMAIL,CUS_TAXID,CUS_MBRTYPE?)>
<!ELEMENT CUS_ID	(#PCDATA )>
<!ELEMENT CUS_DATEIN 	(#PCDATA )>
<!ELEMENT CUS_LNAME 	(#PCDATA )>
<!ELEMENT CUS_FNAME 	(#PCDATA )>
<!ELEMENT CUS_ADDR1	(#PCDATA )>
<!ELEMENT CUS_ADDR2	(#PCDATA )>
<!ELEMENT CUS_CITY	(#PCDATA )>
<!ELEMENT CUS_STATE	(#PCDATA )>
<!ELEMENT CUS_ZIP	(#PCDATA )>
<!ELEMENT CUS_CNTRY	(#PCDATA )>
<!ELEMENT CUS_PHONE	(#PCDATA )>
<!ELEMENT CUS_EMAIL	(#PCDATA )>
<!ELEMENT CUS_TAXID	(#PCDATA )>
<!ELEMENT CUS_MBRTYPE	(#PCDATA )>

=== markus-bcit/term1/Term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/customer.xml
<?xml version ="1.0"?>
<!DOCTYPE Customerdata SYSTEM "Customer.dtd">
<Customerdata>
<Customer>
<CUS_ID>1010</CUS_ID>
<CUS_DATEIN>12/09/2015</CUS_DATEIN>
<CUS_LNAME>SMITH</CUS_LNAME>
<CUS_FNAME>JOHN</CUS_FNAME>
<CUS_ADDR1>123 MAIN ST. </CUS_ADDR1>
<CUS_CITY>MURRAY</CUS_CITY>
<CUS_STATE>FL</CUS_STATE>
<CUS_ZIP>34563</CUS_ZIP>
<CUS_PHONE>305-676-8886</CUS_PHONE>
<CUS_EMAIL>jsmith@yahoo.com</CUS_EMAIL>
<CUS_TAXID>456-83988</CUS_TAXID>
<CUS_MBRTYPE>Gold</CUS_MBRTYPE>
</Customer>
<Customer>
<CUS_ID>1012</CUS_ID>
<CUS_DATEIN>12/10/2015</CUS_DATEIN>
<CUS_LNAME>Blue</CUS_LNAME>
<CUS_FNAME>Gary</CUS_FNAME>
<CUS_ADDR1>1244 Church St.</CUS_ADDR1>
<CUS_CITY>Jakson</CUS_CITY>
<CUS_STATE>TN</CUS_STATE>
<CUS_ZIP>37433</CUS_ZIP>
<CUS_PHONE>678-346-9868</CUS_PHONE>
<CUS_EMAIL>gblue@hotmail.com</CUS_EMAIL>
<CUS_TAXID>345-66583</CUS_TAXID>
</Customer>
</Customerdata>
