=== markus-bcit/term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/promotion.dtd
<!ELEMENT Promotiondata (Promotion+)>
<!ELEMENT Promotion (PROMO_ID,PROMO_NAME,PROMO_DATE,PROMO_BEGDATE,PROMO_ENDDATE,PTYPE_ID?,
 PROD_ID?,PROMO_MINQTY?,PROMO_MAXQTY?,PROMO_MINPUR?,PROMO_PCTDISC?,
 PROMO_DOLLAR?,PROMO_CEILING?)>
<!ELEMENT PROMO_ID (#PCDATA)>
<!ELEMENT PROMO_NAME (#PCDATA)>
<!ELEMENT PROMO_DATE (#PCDATA)>
<!ELEMENT PROMO_BEGDATE (#PCDATA)>
<!ELEMENT PROMO_ENDDATE (#PCDATA)>
<!ELEMENT PTYPE_ID (#PCDATA)>
<!ELEMENT PROD_ID (#PCDATA)>
<!ELEMENT PROMO_MINQTY (#PCDATA)>
<!ELEMENT PROMO_MAXQTY (#PCDATA)>
<!ELEMENT PROMO_MINPUR (#PCDATA)>
<!ELEMENT PROMO_PCTDISC (#PCDATA)>
<!ELEMENT PROMO_DOLLAR (#PCDATA)>
<!ELEMENT PROMO_CEILING (#PCDATA)>

=== markus-bcit/term1/Term1/ACIT 1630 Database Systems/Database Systems/Data Files/XML/CH15/promotion.xml
<?xml version ="1.0"?>
<!DOCTYPE Promotiondata SYSTEM "Promotion.dtd">
<Promotiondata>
<Promotion>
<PROMO_ID>6592</PROMO_ID>
<PROMO_NAME>Christmas Savings</PROMO_NAME>
<PROMO_DATE>11/15/2015</PROMO_DATE>
<PROMO_BEGDATE>12/01/2015</PROMO_BEGDATE>
<PROMO_ENDDATE>12/26/2015</PROMO_ENDDATE>
<PTYPE_ID>Tools</PTYPE_ID>
<PROMO_PCTDISC>20</PROMO_PCTDISC>
</Promotion>
<Promotion>
<PROMO_ID>6759</PROMO_ID>
<PROMO_NAME>Father's Day</PROMO_NAME>
<PROMO_DATE>06/01/2015</PROMO_DATE>
<PROMO_BEGDATE>06/01/2015</PROMO_BEGDATE>
<PROMO_ENDDATE>06/15/2015</PROMO_ENDDATE>
<PTYPE_ID>Electronics</PTYPE_ID>
<PROMO_MINQTY>1</PROMO_MINQTY>
<PROMO_MAXQTY>2</PROMO_MAXQTY>
<PROMO_PCTDISC>50</PROMO_PCTDISC>
</Promotion>
<Promotion>
<PROMO_ID>7845</PROMO_ID>
<PROMO_NAME>Drill Specials</PROMO_NAME>
<PROMO_DATE>08/01/2015</PROMO_DATE>
<PROMO_BEGDATE>08/01/2015</PROMO_BEGDATE>
<PROMO_ENDDATE>08/15/2015</PROMO_ENDDATE>
<PROD_ID>QWERT-456</PROD_ID>
<PROMO_PCTDISC>10</PROMO_PCTDISC>
</Promotion>
<Promotion>
<PROMO_ID>7789</PROMO_ID>
<PROMO_NAME>$25 Buying Spree</PROMO_NAME>
<PROMO_DATE>09/01/2015</PROMO_DATE>
<PROMO_BEGDATE>06/01/2015</PROMO_BEGDATE>
<PROMO_ENDDATE>05/31/2016</PROMO_ENDDATE>
<PROMO_DOLLAR>25</PROMO_DOLLAR>
</Promotion>
</Promotiondata>
